export interface ActeParamLabo {
    _id: string;
    IDPARAM_LABO?: string;
    IDACTEP?: string;
    PlageMaxEnfant?: number;
    PlageMinEnfant?: number;
    PlageMinMaxEnfant?: string;
    PLageMinFemme?: number;
    PlageMaxFemme?: number;
    PlageMinMaxFemme?: string;
    PlageMinHomme?: number;
    PlageMaxHomme?: number;
    PlageMinMaxHomme?: string;
    PlageMinMaxNé?: string;
    PlageRefMinNe?: number;
    PlageRefMaxNé?: number;
    NUM_PARAM?: number;
    Param_designation?: string;
    ParamAbrege?: string;
    UnitéParam?: string;
    ValeurNormale?: string;
    ValeurMaxNormale?: number;
    ValeurMinNormale?: number;
    TypeTexte?: boolean;
    SigneNormale?: string;
    SigneNé?: string;
    SigneEnfant?: string;
    SigneFemme?: string;
    SigneHomme?: string;
    ORdonnacementAffichage?:number;
}
