// Register all tenant models so their schemas are available to getTenantModel
export * from './ActeParametre';
export * from './Approvisionnement';
export * from './AvisHospit';
export * from './BiochimieTraitement';
export * from './CommandeFournisseur';
export * from './ComptePatient';
export * from './EncaissementCaisse';
export * from './EncaissementCaisseAnnule';
export * from './EntreeStock';
export * from './Facturation';
export * from './FeuilleSoins';
export * from './Fournisseur';
export * from './HistoriqueInventaire';
export * from './HonoraireMed';
export * from './HonorairePaye';
export * from './HormoneTraitement';
export * from './LigneHonoraireMed';
export * from './LigneInventaire';
export * from './ModeDePaiement';
export * from './ObservationHospit';
export * from './ParametreCRendu';
export * from './PatientPrescription';
export * from './Pharmacie';
export * from './PlanningMed';
export * from './Prescription';
export * from './RendezVous';
export * from './SocieteAssurance';
export * from './SocietePartenaire';
export * from './SortieStock';
export * from './Stock';
export * from './Testimonial';
export * from './TypeActe';
export * from './VitesseTraitement';
export * from './acteParamBiochimie';
export * from './acteParamLabo';
export * from './acteSocietePartenaire';
export * from './acteclinique';
export * from './affection';
export * from './arretTravail';
export * from './assurance';
export * from './caisse';
export * from './chambre';
export * from './compteRenduOperatoire';
export * from './consultation';
export * from './documentFichePatient';
export * from './documentpatient';
export * from './entreprise';
export * from './examenHospit';
export * from './factureAssur';
export * from './factureRecap';
export * from './familleActe';
export * from './infirmier';
export * from './inventaire';
export * from './journalConnexion';
export * from './lienAutomate';
export * from './ligneFacture';
export * from './lignePrestation';
export * from './lit';
export * from './medecin';
export * from './nfsTraitement';
export * from './operation';
export * from './paiementPartenaire';
export * from './paramBiochimie';
export * from './paramLabo';
export * from './parametreNfs';
export * from './patient';
export * from './rapportHospitalisation';
export * from './resultatLignePrestation';
export * from './tarifassurance';
export * from './users.model';

// Side-effect imports ensure schemas are registered with default mongoose
import './ActeParametre';
import './Approvisionnement';
import './AvisHospit';
import './BiochimieTraitement';
import './CommandeFournisseur';
import './ComptePatient';
import './EncaissementCaisse';
import './EncaissementCaisseAnnule';
import './EntreeStock';
import './Facturation';
import './FeuilleSoins';
import './Fournisseur';
import './HistoriqueInventaire';
import './HonoraireMed';
import './HonorairePaye';
import './HormoneTraitement';
import './LigneHonoraireMed';
import './LigneInventaire';
import './ModeDePaiement';
import './ObservationHospit';
import './ParametreCRendu';
import './PatientPrescription';
import './Pharmacie';
import './PlanningMed';
import './Prescription';
import './RendezVous';
import './SocieteAssurance';
import './SocietePartenaire';
import './SortieStock';
import './Stock';
import './Testimonial';
import './TypeActe';
import './VitesseTraitement';
import './acteParamBiochimie';
import './acteParamLabo';
import './acteSocietePartenaire';
import './acteclinique';
import './affection';
import './arretTravail';
import './assurance';
import './caisse';
import './chambre';
import './compteRenduOperatoire';
import './consultation';
import './documentFichePatient';
import './documentpatient';
import './entreprise';
import './examenHospit';
import './factureAssur';
import './factureRecap';
import './familleActe';
import './infirmier';
import './inventaire';
import './journalConnexion';
import './lienAutomate';
import './ligneFacture';
import './lignePrestation';
import './lit';
import './medecin';
import './nfsTraitement';
import './operation';
import './paiementPartenaire';
import './paramBiochimie';
import './paramLabo';
import './parametreNfs';
import './patient';
import './rapportHospitalisation';
import './resultatLignePrestation';
import './tarifassurance';
import './users.model';

// --- Modèles du module Hospitalisation ---
export * from './hospitalisation/ConstanteHospitalisation';
export * from './hospitalisation/PrescriptionHospitalisation';
export * from './hospitalisation/SoinHospitalisation';
export * from './hospitalisation/EvolutionMedicaleHospitalisation';
export * from './hospitalisation/DocumentHospitalisation';
export * from './hospitalisation/MouvementHospitalisation';
export * from './hospitalisation/FactureHospitalisation';

import './hospitalisation/ConstanteHospitalisation';
import './hospitalisation/PrescriptionHospitalisation';
import './hospitalisation/SoinHospitalisation';
import './hospitalisation/EvolutionMedicaleHospitalisation';
import './hospitalisation/DocumentHospitalisation';
import './hospitalisation/MouvementHospitalisation';
import './hospitalisation/FactureHospitalisation';
